# Generated by Django 5.2.6 on 2026-02-22 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_add_default_change_interval_km_to_subcategory'),
        ('inventory', '0001_add_default_change_interval_km_to_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії робіт')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
            options={
                'verbose_name': 'Група робіт',
                'verbose_name_plural': 'Групи робіт',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Кількість оливи')),
                ('oil_change_interval_km', models.PositiveIntegerField(blank=True, help_text='Наприклад: 20000', null=True, verbose_name='Інтервал заміни оливи (км)')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oil_for_trucks', to='inventory.product', verbose_name='Олива')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Комплект ТО',
                'verbose_name_plural': 'Комплекти ТО',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceKitFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('change_interval_km', models.PositiveIntegerField(blank=True, help_text='Наприклад: 20000', null=True, verbose_name='Інтервал заміни (км)')),
                ('maintenance_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='orders.maintenancekit', verbose_name='Комплект ТО')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Запчастина')),
            ],
            options={
                'verbose_name': 'Фільтр комплекту ТО',
                'verbose_name_plural': 'Фільтри комплектів ТО',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('km_interval', models.PositiveIntegerField(verbose_name='Інтервал (км)')),
                ('applicable_models', models.ManyToManyField(to='clients.ivecobasemodel', verbose_name='Застосовні моделі')),
            ],
            options={
                'verbose_name': 'Правило ТО',
                'verbose_name_plural': 'Правила ТО',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(verbose_name='Дата виконання')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.maintenancerule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Запис ТО',
                'verbose_name_plural': 'Записи ТО',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('current_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Поточний пробіг')),
                ('problem_description', models.TextField(blank=True, verbose_name='Опис проблеми')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендації')),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='order_photos/cars/')),
                ('odometer_photo', models.ImageField(blank=True, null=True, upload_to='order_photos/odometers/')),
                ('dashboard_photo', models.ImageField(blank=True, null=True, upload_to='order_photos/dashboards/')),
                ('status', models.CharField(choices=[('OPEN', 'Відкрито'), ('IN_PROGRESS', 'В роботі'), ('DONE', 'Виконано'), ('CLOSED', 'Закрито'), ('CANCELED', 'Скасовано')], default='OPEN', max_length=20, verbose_name='Статус')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна вартість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('marked_for_deletion', models.BooleanField(default=False, verbose_name='Позначено на видалення')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Причина видалення')),
                ('marked_for_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата позначення')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клієнт')),
                ('marked_for_deletion_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Наряд-замовлення',
                'verbose_name_plural': 'Наряди-замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='repair_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.serviceorder')),
            ],
            options={
                'verbose_name': 'Фото ремонту',
                'verbose_name_plural': 'Фото ремонтів',
            },
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва роботи')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.workgroup')),
            ],
            options={
                'verbose_name': 'Робота',
                'verbose_name_plural': 'Роботи',
            },
        ),
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('hours_spent', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Витрачено годин')),
                ('price_at_moment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Механік')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.serviceorder', verbose_name='Наряд-замовлення')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workprice', verbose_name='Робота')),
            ],
            options={
                'verbose_name': 'Виконана робота',
                'verbose_name_plural': 'Виконані роботи',
            },
        ),
    ]
