# Generated by Django 5.2.6 on 2025-09-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я та прізвище")),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва регламентної роботи')),
                ('interval_km', models.PositiveIntegerField(verbose_name='Інтервал пробігу (км)')),
                ('applicable_transmission', models.CharField(choices=[('any', 'Будь-яка'), ('manual', 'Механічна'), ('automatic', 'Автоматична'), ('robot', 'Робот')], default='any', max_length=10, verbose_name='Застосовується до типу КПП')),
                ('applicable_models', models.ManyToManyField(to='clients.ivecobasemodel', verbose_name='Застосовується до базових моделей')),
            ],
            options={
                'verbose_name': 'Правило регламенту',
                'verbose_name_plural': 'Правила регламентів',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(auto_now_add=True, verbose_name='Дата виконання')),
                ('completion_mileage', models.PositiveIntegerField(verbose_name='Пробіг на момент виконання (км)')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.maintenancerule', verbose_name='Виконане правило')),
            ],
            options={
                'verbose_name': 'Запис у журналі регламенту',
                'verbose_name_plural': 'Журнал регламентних робіт',
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Причина звернення / Скарги клієнта')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата відкриття')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закриття')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна вартість')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Замовлення-наряд',
                'verbose_name_plural': 'Замовлення-наряди',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(max_length=255, verbose_name='Опис роботи')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість роботи')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Витрачено годин')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.employee', verbose_name='Виконавець')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.serviceorder', verbose_name='Замовлення-наряд')),
            ],
            options={
                'verbose_name': 'Виконана робота',
                'verbose_name_plural': 'Виконані роботи',
            },
        ),
    ]
