# Generated by Django 5.2.6 on 2025-09-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва групи робіт')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість нормогодини (грн)')),
            ],
            options={
                'verbose_name': 'Група робіт',
                'verbose_name_plural': 'Групи робіт',
            },
        ),
        migrations.AlterField(
            model_name='servicework',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Розраховується автоматично, але може бути змінена вручну.', max_digits=10, verbose_name='Вартість роботи'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='work_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.workgroup', verbose_name='Група робіт'),
        ),
    ]
