# Generated by Django 5.2.6 on 2025-09-17 20:09

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_workgroup_alter_servicework_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/cars/', verbose_name='Фото авто з держномером'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='odometer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/odometers/', verbose_name='Фото щитка приладів'),
        ),
        migrations.CreateModel(
            name='RepairPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models.get_repair_photo_path, verbose_name='Фото ремонту')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Короткий опис')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_photos', to='orders.serviceorder')),
            ],
        ),
    ]
