# Generated by Django 5.2.6 on 2026-02-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_serviceorder_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='З статусу')),
                ('to_status', models.CharField(max_length=20, verbose_name='На статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Час зміни')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.serviceorder', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Зміна статусу',
                'verbose_name_plural': 'Зміни статусу',
                'ordering': ['changed_at'],
            },
        ),
    ]
