# Generated by Django 5.2.6 on 2025-10-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_serviceorder_car_photo_serviceorder_odometer_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва роботи')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість роботи (грн)')),
            ],
            options={
                'verbose_name': 'Робота з прайсу',
                'verbose_name_plural': 'Роботи з прайсу',
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва категорії робіт')),
            ],
            options={
                'verbose_name': 'Категорія робіт',
                'verbose_name_plural': 'Категорії робіт',
            },
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='work_group',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='labor_cost',
        ),
        migrations.AddField(
            model_name='servicework',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фактична вартість'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='custom_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис/уточнення'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.work', verbose_name='Виконана робота'),
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.workcategory', verbose_name='Категорія'),
        ),
        migrations.DeleteModel(
            name='WorkGroup',
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('category', 'name')},
        ),
    ]
