# Generated by Django 5.2.6 on 2025-10-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_work_workcategory_remove_servicework_work_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='price',
        ),
        migrations.AddField(
            model_name='servicework',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Витрачено годин'),
        ),
        migrations.AddField(
            model_name='work',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість нормогодини (грн)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.work', verbose_name='Виконана робота'),
        ),
    ]
