# Generated by Django 5.2.6 on 2026-02-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0002_initial'),
        ('orders', '0004_add_order_status_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMaintenanceKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro_standard', models.CharField(blank=True, choices=[('', 'Будь-який'), ('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], default='', max_length=10, verbose_name='Стандарт Євро')),
                ('oil_quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Кількість оливи')),
                ('oil_change_interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни оливи (км)')),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_kits', to='clients.ivecobasemodel', verbose_name='Базова модель')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_oil_for_kits', to='inventory.product', verbose_name='Олива')),
            ],
            options={
                'verbose_name': 'Базовий комплект ТО',
                'verbose_name_plural': 'Базові комплекти ТО',
                'unique_together': {('base_model', 'euro_standard')},
            },
        ),
        migrations.CreateModel(
            name='BaseMaintenanceKitFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('change_interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни (км)')),
                ('base_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='orders.basemaintenancekit', verbose_name='Базовий комплект ТО')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Запчастина')),
            ],
            options={
                'verbose_name': 'Фільтр базового комплекту ТО',
                'verbose_name_plural': 'Фільтри базових комплектів ТО',
            },
        ),
    ]
