# Generated by Django 5.2.6 on 2026-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_base_maintenance_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemaintenancekitfilter',
            name='service_type',
            field=models.CharField(choices=[('both', 'Повне і часткове ТО'), ('full', 'Тільки повне ТО'), ('partial', 'Тільки часткове ТО')], default='both', help_text='В якому виді ТО використовується цей фільтр', max_length=10, verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='maintenancekitfilter',
            name='service_type',
            field=models.CharField(choices=[('both', 'Повне і часткове ТО'), ('full', 'Тільки повне ТО'), ('partial', 'Тільки часткове ТО')], default='both', help_text='В якому виді ТО використовується цей фільтр', max_length=10, verbose_name='Вид ТО'),
        ),
    ]
