# Generated by Django 5.2.6 on 2025-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_work_price_servicework_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер наряду-замовлення'),
        ),
    ]
