# Generated by Django 5.2.6 on 2025-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_serviceorder_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='workcategory',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість нормогодини (грн)'),
        ),
    ]
