# Generated by Django 5.2.6 on 2025-10-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_work_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='dashboard_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/dashboards/', verbose_name='Фото панелі приладів'),
        ),
    ]
