# Generated by Django 5.2.6 on 2025-11-12 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_created_at_remove_client_surname_and_more'),
        ('orders', '0008_serviceorder_dashboard_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії робіт')),
            ],
            options={
                'verbose_name': 'Категорія робіт',
                'verbose_name_plural': 'Категорії робіт',
            },
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='work',
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'verbose_name': 'Журнал регламентних робіт', 'verbose_name_plural': 'Журнал регламентних робіт'},
        ),
        migrations.AlterModelOptions(
            name='repairphoto',
            options={'verbose_name': 'Фото ремонту', 'verbose_name_plural': 'Фото ремонту'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Замовлення-наряд', 'verbose_name_plural': 'Замовлення-наряди'},
        ),
        migrations.RenameField(
            model_name='servicework',
            old_name='duration_hours',
            new_name='hours_spent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='completion_mileage',
        ),
        migrations.RemoveField(
            model_name='maintenancerule',
            name='applicable_transmission',
        ),
        migrations.RemoveField(
            model_name='maintenancerule',
            name='interval_km',
        ),
        migrations.RemoveField(
            model_name='repairphoto',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='repairphoto',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='car_photo',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='dashboard_photo',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='odometer_photo',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicework',
            name='custom_description',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='date_performed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата виконання'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='description',
            field=models.TextField(default='', verbose_name='Опис'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='problem_description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис проблеми (зі слів клієнта)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='description',
            field=models.TextField(default='', verbose_name='Опис виконаних робіт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.maintenancerule', verbose_name='Правило регламенту'),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='applicable_models',
            field=models.ManyToManyField(to='clients.ivecobasemodel', verbose_name='Застосовується до моделей'),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва правила'),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='image',
            field=models.ImageField(upload_to='repair_photos/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.serviceorder', verbose_name='Замовлення-наряд'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер замовлення-наряду'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Відкрито'), ('IN_PROGRESS', 'В роботі'), ('CLOSED', 'Закрито'), ('CANCELED', 'Скасовано')], default='OPEN', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.truck', verbose_name='Вантажівка'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.employee', verbose_name='Виконавець'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='work_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workgroup', verbose_name='Категорія робіт'),
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва роботи')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.workgroup', verbose_name='Категорія робіт')),
            ],
            options={
                'verbose_name': 'Робота з прайсу',
                'verbose_name_plural': 'Роботи з прайсу',
            },
        ),
        migrations.DeleteModel(
            name='WorkCategory',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
