# Generated by Django 5.2.6 on 2025-11-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_workgroup_alter_work_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicework',
            name='work_group',
        ),
        migrations.AddField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workprice', verbose_name='Виконана робота (з прайсу)'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='description',
            field=models.TextField(verbose_name='Опис виконаних робіт (додатково)'),
        ),
    ]
