# Generated by Django 5.2.6 on 2025-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_servicework_work_group_servicework_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerule',
            name='km_interval',
            field=models.PositiveIntegerField(default=0, help_text='Через яку кількість кілометрів потрібно виконувати це правило', verbose_name='Інтервал (км)'),
            preserve_default=False,
        ),
    ]
