# Generated by Django 5.2.6 on 2025-11-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_maintenancerule_km_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
    ]
