# Generated by Django 5.2.6 on 2025-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_maintenancerule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicework',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис виконаних робіт (додатково)'),
        ),
    ]
