# Generated by Django 5.2.6 on 2025-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_servicework_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicework',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Витрачено годин'),
        ),
    ]
