# Generated by Django 5.2.6 on 2025-11-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_servicework_hours_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.AlterModelOptions(
            name='workprice',
            options={'ordering': ['name'], 'verbose_name': 'Робота з прайсу', 'verbose_name_plural': 'Роботи з прайсу'},
        ),
    ]
