# Generated by Django 5.2.6 on 2025-11-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_ivecobasemodel_options'),
        ('orders', '0015_alter_employee_options_alter_workprice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='truck',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='clients.truck', verbose_name='Вантажівка'),
        ),
    ]
