# Generated by Django 5.2.6 on 2025-11-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_ivecobasemodel_options'),
        ('orders', '0016_alter_serviceorder_client_alter_serviceorder_truck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-date_performed'], 'verbose_name': 'Журнал регламентних робіт', 'verbose_name_plural': 'Журнал регламентних робіт'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerule',
            options={'ordering': ['name'], 'verbose_name': 'Правило регламенту', 'verbose_name_plural': 'Правила регламентів'},
        ),
        migrations.AlterModelOptions(
            name='repairphoto',
            options={'ordering': ['-service_order'], 'verbose_name': 'Фото ремонту', 'verbose_name_plural': 'Фото ремонту'},
        ),
        migrations.AlterModelOptions(
            name='servicework',
            options={'ordering': ['-service_order'], 'verbose_name': 'Виконана робота', 'verbose_name_plural': 'Виконані роботи'},
        ),
        migrations.AlterModelOptions(
            name='workgroup',
            options={'ordering': ['name'], 'verbose_name': 'Категорія робіт', 'verbose_name_plural': 'Категорії робіт'},
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна вартість'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.truck', verbose_name='Вантажівка'),
        ),
    ]
