# Generated by Django 5.2.6 on 2025-11-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_ivecobasemodel_options'),
        ('inventory', '0005_part_address_in_stock_part_notes'),
        ('orders', '0017_alter_maintenancelog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprice',
            name='price',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Вартість нормо-години (грн)'),
        ),
        migrations.AddField(
            model_name='workprice',
            name='standard_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Нормо-годин (стандартна тривалість)'),
        ),
        migrations.CreateModel(
            name='MaintenanceKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Кількість оливи (л)')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('air_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='air_filters_for_trucks', to='inventory.part', verbose_name='Повітряний фільтр')),
                ('cabin_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cabin_filters_for_trucks', to='inventory.part', verbose_name='Салонний фільтр')),
                ('fuel_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_filters_for_trucks', to='inventory.part', verbose_name='Паливний фільтр')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oil_for_trucks', to='inventory.part', verbose_name='Моторна олива')),
                ('oil_filter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oil_filters_for_trucks', to='inventory.part', verbose_name='Масляний фільтр')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_kit', to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Набір для ТО',
                'verbose_name_plural': 'Набори для ТО',
            },
        ),
    ]
