# Generated by Django 5.2.6 on 2026-04-30 07:27

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_maintenanceintervalstemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemaintenancekitfilter',
            name='service_type',
            field=models.CharField(choices=[('both', 'Повне і часткове ТО'), ('full', 'Тільки повне ТО'), ('partial', 'Тільки часткове ТО'), ('rear_axle', 'Заміна оливи заднього моста'), ('gearbox', 'Заміна оливи КПП'), ('auto_gearbox', 'Заміна оливи АКПП'), ('auto_gearbox_filter', 'Заміна фільтра АКПП'), ('belts', 'Заміна ремнів/роликів'), ('chains', 'Заміна ланцюгів')], default='both', help_text='В якому виді ТО використовується цей фільтр', max_length=20, verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenanceintervalstemplate',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('', 'Будь-який'), ('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], default='', help_text='Залиште порожнім, щоб еталон підходив до будь-якого євростандарту', max_length=10, verbose_name='Євростандарт'),
        ),
        migrations.AlterField(
            model_name='maintenanceintervalstemplate',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('', 'Будь-який'), ('manual', 'Механічна'), ('automatic', 'Автоматична'), ('robotic', 'Роботизована')], default='', help_text='Залиште порожнім, щоб еталон підходив до будь-якої КПП', max_length=10, verbose_name='Тип КПП'),
        ),
        migrations.AlterField(
            model_name='maintenancekitfilter',
            name='service_type',
            field=models.CharField(choices=[('both', 'Повне і часткове ТО'), ('full', 'Тільки повне ТО'), ('partial', 'Тільки часткове ТО'), ('rear_axle', 'Заміна оливи заднього моста'), ('gearbox', 'Заміна оливи КПП'), ('auto_gearbox', 'Заміна оливи АКПП'), ('auto_gearbox_filter', 'Заміна фільтра АКПП'), ('belts', 'Заміна ремнів/роликів'), ('chains', 'Заміна ланцюгів')], default='both', help_text='В якому виді ТО використовується цей фільтр', max_length=20, verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='image',
            field=models.ImageField(upload_to=orders.models.get_repair_photo_path, validators=[orders.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='truckmaintenanceintervals',
            name='gearbox_oil_interval',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни оливи КПП (км)'),
        ),
        migrations.AlterField(
            model_name='truckmaintenanceintervals',
            name='gearbox_oil_last_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг при останній заміні оливи КПП'),
        ),
    ]
