# Generated by Django 5.2.6 on 2025-11-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_ivecobasemodel_options'),
        ('inventory', '0005_part_address_in_stock_part_notes'),
        ('orders', '0018_remove_workprice_price_workgroup_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва типу фільтра')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('replacement_interval_km', models.PositiveIntegerField(default=20000, help_text='Стандартний інтервал заміни для цього типу', verbose_name='Інтервал заміни (км)')),
            ],
            options={
                'verbose_name': 'Тип фільтра',
                'verbose_name_plural': 'Типи фільтрів',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='air_filter',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='cabin_filter',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='fuel_filter',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='oil_filter',
        ),
        migrations.AddField(
            model_name='maintenancekit',
            name='oil_replacement_interval',
            field=models.PositiveIntegerField(default=30000, verbose_name='Інтервал заміни оливи (км)'),
        ),
        migrations.AlterField(
            model_name='maintenancekit',
            name='truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_kit', to='clients.truck', verbose_name='Вантажівка (по VIN)'),
        ),
        migrations.CreateModel(
            name='MaintenanceKitFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Скільки таких фільтрів потрібно', verbose_name='Кількість')),
                ('custom_interval_km', models.PositiveIntegerField(blank=True, help_text='Залиште порожнім для використання стандартного інтервалу типу', null=True, verbose_name='Індивідуальний інтервал (км)')),
                ('notes', models.CharField(blank=True, help_text="Наприклад: 'грубої очистки', 'тонкої очистки'", max_length=255, verbose_name='Примітка')),
                ('filter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.filtertype', verbose_name='Тип фільтра')),
                ('maintenance_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='orders.maintenancekit', verbose_name='Набір ТО')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part', verbose_name='Запчастина (фільтр)')),
            ],
            options={
                'verbose_name': 'Фільтр у наборі',
                'verbose_name_plural': 'Фільтри у наборі',
                'ordering': ['filter_type__name'],
            },
        ),
    ]
