# Generated by Django 5.2.6 on 2026-04-30 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_barcode'),
        ('orders', '0019_add_choices_to_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='auto_gearbox_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_auto_gearbox_filter', to='inventory.product', verbose_name='Фільтр АКПП'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='auto_gearbox_filter_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість фільтрів АКПП'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='auto_gearbox_oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_auto_gearbox_oil', to='inventory.product', verbose_name='Олива АКПП'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='auto_gearbox_oil_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кількість оливи АКПП'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='gearbox_oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_gearbox_oil', to='inventory.product', verbose_name='Олива КПП'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='gearbox_oil_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кількість оливи КПП'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_oil', to='inventory.product', verbose_name='Олива двигуна'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='oil_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кількість оливи двигуна'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='rear_axle_oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_rear_axle_oil', to='inventory.product', verbose_name='Олива заднього моста'),
        ),
        migrations.AddField(
            model_name='maintenanceintervalstemplate',
            name='rear_axle_oil_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кількість оливи заднього моста'),
        ),
        migrations.CreateModel(
            name='TemplateKitFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('change_interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни (км)')),
                ('service_type', models.CharField(choices=[('both', 'Повне і часткове ТО'), ('full', 'Тільки повне ТО'), ('partial', 'Тільки часткове ТО'), ('rear_axle', 'Заміна оливи заднього моста'), ('gearbox', 'Заміна оливи КПП'), ('auto_gearbox', 'Заміна оливи АКПП'), ('auto_gearbox_filter', 'Заміна фільтра АКПП'), ('belts', 'Заміна ремнів/роликів'), ('chains', 'Заміна ланцюгів')], default='both', help_text='В якому виді ТО використовується цей фільтр', max_length=20, verbose_name='Вид ТО')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Запчастина')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='orders.maintenanceintervalstemplate', verbose_name='Еталон ТО')),
            ],
            options={
                'verbose_name': 'Фільтр еталонного комплекту ТО',
                'verbose_name_plural': 'Фільтри еталонного комплекту ТО',
            },
        ),
    ]
