# Generated by Django 5.2.6 on 2025-11-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_truck_euro_standard'),
        ('orders', '0019_filtertype_remove_maintenancekit_air_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtertype',
            name='applicable_models',
            field=models.ManyToManyField(blank=True, help_text='Залиште порожнім якщо підходить для всіх моделей', to='clients.ivecobasemodel', verbose_name='Застосовується до моделей'),
        ),
        migrations.AddField(
            model_name='filtertype',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], help_text='Залиште порожнім якщо підходить для всіх стандартів', max_length=10, null=True, verbose_name='Євростандарт'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва типу фільтра'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='replacement_interval_km',
            field=models.PositiveIntegerField(default=15000, help_text='Стандартний інтервал заміни для цього типу', verbose_name='Інтервал заміни (км)'),
        ),
    ]
