# Generated by Django 5.2.6 on 2025-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_filtertype_applicable_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtertype',
            name='replacement_interval_km',
            field=models.PositiveIntegerField(default=20000, help_text='Стандартний інтервал заміни для цього типу', verbose_name='Інтервал заміни (км)'),
        ),
    ]
