# Generated by Django 5.2.6 on 2026-06-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_add_oils_and_filters_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerule',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_rules', to='orders.workprice', verbose_name='Послуга з довідника'),
        ),
    ]
