# Generated by Django 5.2.6 on 2026-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_filtertype_replacement_interval_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Поточний пробіг (км)'),
        ),
    ]
