# Generated by Django 5.2.6 on 2026-01-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_deletion_reason_client_marked_for_deletion_and_more'),
        ('orders', '0023_serviceorder_car_photo_serviceorder_dashboard_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicework',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='repairphoto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicework',
            options={'verbose_name': 'Робота в наряді', 'verbose_name_plural': 'Роботи в наряді'},
        ),
        migrations.AddField(
            model_name='servicework',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Механік'),
        ),
        migrations.AddField(
            model_name='servicework',
            name='price_at_moment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна (фіксована)'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='applicable_models',
            field=models.ManyToManyField(blank=True, to='clients.ivecobasemodel', verbose_name='Застосовується до моделей'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], max_length=10, null=True, verbose_name='Євростандарт'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='replacement_interval_km',
            field=models.PositiveIntegerField(default=20000, verbose_name='Інтервал заміни (км)'),
        ),
        migrations.AlterField(
            model_name='maintenancekit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenancekit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenancekitfilter',
            name='custom_interval_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Індивідуальний інтервал (км)'),
        ),
        migrations.AlterField(
            model_name='maintenancekitfilter',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='maintenancekitfilter',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='image',
            field=models.ImageField(upload_to='repair_photos/'),
        ),
        migrations.AlterField(
            model_name='repairphoto',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.serviceorder'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/cars/', verbose_name='Фото авто/номера'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клієнт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг при заїзді (км)'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='marked_for_deletion',
            field=models.BooleanField(default=False, verbose_name='Видалити?'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер наряду'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='problem_description',
            field=models.TextField(blank=True, default=1, verbose_name='Скарги клієнта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Відкрито'), ('IN_PROGRESS', 'В роботі'), ('DONE', 'Виконано (Очікує оплати)'), ('CLOSED', 'Закрито (Оплачено)'), ('CANCELED', 'Скасовано')], default='OPEN', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна вартість'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.truck', verbose_name='Вантажівка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Додатковий опис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicework',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.serviceorder', verbose_name='Наряд'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workprice', verbose_name='Робота з прайсу'),
        ),
        migrations.AlterField(
            model_name='workprice',
            name='standard_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Нормо-годин'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
