# Generated by Django 5.2.6 on 2026-01-31 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_deletion_reason_client_marked_for_deletion_and_more'),
        ('inventory', '0010_delete_productsubcategory_delete_stock'),
        ('orders', '0024_remove_servicework_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtertype',
            options={'verbose_name': 'Тип фільтра', 'verbose_name_plural': 'Типи фільтрів'},
        ),
        migrations.AlterModelOptions(
            name='maintenancekit',
            options={'verbose_name': 'Комплект ТО', 'verbose_name_plural': 'Комплекти ТО'},
        ),
        migrations.AlterModelOptions(
            name='maintenancekitfilter',
            options={'verbose_name': 'Фільтр комплекту ТО', 'verbose_name_plural': 'Фільтри комплектів ТО'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'verbose_name': 'Запис ТО', 'verbose_name_plural': 'Записи ТО'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerule',
            options={'verbose_name': 'Правило ТО', 'verbose_name_plural': 'Правила ТО'},
        ),
        migrations.AlterModelOptions(
            name='repairphoto',
            options={'verbose_name': 'Фото ремонту', 'verbose_name_plural': 'Фото ремонтів'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Наряд-замовлення', 'verbose_name_plural': 'Наряди-замовлення'},
        ),
        migrations.AlterModelOptions(
            name='servicework',
            options={'verbose_name': 'Виконана робота', 'verbose_name_plural': 'Виконані роботи'},
        ),
        migrations.AlterModelOptions(
            name='workgroup',
            options={'verbose_name': 'Група робіт', 'verbose_name_plural': 'Групи робіт'},
        ),
        migrations.AlterModelOptions(
            name='workprice',
            options={'verbose_name': 'Робота', 'verbose_name_plural': 'Роботи'},
        ),
        migrations.RemoveField(
            model_name='filtertype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='oil_replacement_interval',
        ),
        migrations.RemoveField(
            model_name='maintenancekit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='maintenancekitfilter',
            name='custom_interval_km',
        ),
        migrations.RemoveField(
            model_name='maintenancekitfilter',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenancerule',
            name='description',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='applicable_models',
            field=models.ManyToManyField(blank=True, to='clients.ivecobasemodel', verbose_name='Застосовні моделі'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], default=1, max_length=10, verbose_name='Євростандарт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='maintenancekit',
            name='oil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oil_for_trucks', to='inventory.product', verbose_name='Олива'),
        ),
        migrations.AlterField(
            model_name='maintenancekit',
            name='oil_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Кількість оливи'),
        ),
        migrations.AlterField(
            model_name='maintenancekit',
            name='truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка'),
        ),
        migrations.AlterField(
            model_name='maintenancekitfilter',
            name='maintenance_kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='orders.maintenancekit', verbose_name='Комплект ТО'),
        ),
        migrations.AlterField(
            model_name='maintenancekitfilter',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Запчастина'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.maintenancerule', verbose_name='Правило'),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='applicable_models',
            field=models.ManyToManyField(to='clients.ivecobasemodel', verbose_name='Застосовні моделі'),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='km_interval',
            field=models.PositiveIntegerField(verbose_name='Інтервал (км)'),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/cars/'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Поточний пробіг'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='dashboard_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/dashboards/'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='marked_for_deletion',
            field=models.BooleanField(default=False, verbose_name='Позначено на видалення'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='odometer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/odometers/'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='problem_description',
            field=models.TextField(blank=True, verbose_name='Опис проблеми'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Відкрито'), ('IN_PROGRESS', 'В роботі'), ('DONE', 'Виконано'), ('CLOSED', 'Закрито'), ('CANCELED', 'Скасовано')], default='OPEN', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='price_at_moment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.serviceorder', verbose_name='Наряд-замовлення'),
        ),
        migrations.AlterField(
            model_name='servicework',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.workprice', verbose_name='Робота'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workprice',
            name='standard_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workprice',
            name='work_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='orders.workgroup'),
        ),
    ]
