# Generated by Django 5.2.6 on 2025-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('message_text', models.TextField(verbose_name='Повідомлення від користувача')),
                ('bot_response', models.TextField(verbose_name='Відповідь бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
            ],
            options={
                'verbose_name': 'Лог повідомлення',
                'verbose_name_plural': 'Логи повідомлень',
                'ordering': ['-created_at'],
            },
        ),
    ]
