# Generated by Django 5.2.6 on 2025-12-15 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0011_merge_20251215_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, unique=True, verbose_name='Команда')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('required_role', models.CharField(choices=[('guest', 'Гість'), ('driver', 'Водій'), ('owner', 'Власник'), ('manager', 'Менеджер'), ('admin', 'Адміністратор')], default='guest', max_length=20, verbose_name='Мінімальна роль')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Кількість використань')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Остання використана')),
            ],
            options={
                'verbose_name': 'Команда бота',
                'verbose_name_plural': 'Команди бота',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username (@username)')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Прізвище')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути в форматі: '+380501234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону')),
                ('role', models.CharField(choices=[('guest', 'Гість'), ('driver', 'Водій'), ('owner', 'Власник'), ('manager', 'Менеджер'), ('admin', 'Адміністратор')], db_index=True, default='guest', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('block_reason', models.TextField(blank=True, verbose_name='Причина блокування')),
                ('language_code', models.CharField(default='uk', max_length=10, verbose_name='Мова')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Сповіщення увімкнені')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Всього повідомлень')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Остання активність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('assigned_trucks', models.ManyToManyField(blank=True, related_name='drivers', to='clients.truck', verbose_name='Закріплені автомобілі (для водія)')),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_user', to='clients.client', verbose_name='Клієнт CRM')),
            ],
            options={
                'verbose_name': 'Користувач бота',
                'verbose_name_plural': 'Користувачі бота',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(default='idle', max_length=100, verbose_name='Поточний стан')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Контекст розмови')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('bot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='bot.botuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Стан розмови',
                'verbose_name_plural': 'Стани розмов',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('command', 'Команда'), ('contact', 'Контакт'), ('callback', 'Callback кнопка'), ('photo', 'Фото'), ('document', 'Документ'), ('location', 'Локація'), ('other', 'Інше')], default='text', max_length=20, verbose_name='Тип повідомлення')),
                ('is_incoming', models.BooleanField(default=True, verbose_name='Вхідне повідомлення')),
                ('message_text', models.TextField(blank=True, verbose_name='Текст повідомлення')),
                ('message_data', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані (JSON)')),
                ('bot_response', models.TextField(blank=True, verbose_name='Відповідь бота')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Оброблено')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Час обробки (мс)')),
                ('handler_name', models.CharField(blank=True, max_length=100, verbose_name='Назва обробника')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.botuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог повідомлення',
                'verbose_name_plural': 'Логи повідомлень',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('oil_change', 'Заміна оливи'), ('maintenance', 'Планове ТО'), ('part_arrival', 'Прибуття запчастини'), ('service_complete', 'Завершення ремонту'), ('inspection_due', 'Техогляд'), ('insurance_due', 'Страховка'), ('custom', 'Інше')], max_length=50, verbose_name='Тип нагадування')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('advance_days', models.IntegerField(default=3, verbose_name='За скільки днів нагадувати')),
                ('advance_km', models.IntegerField(blank=True, null=True, verbose_name='За скільки км нагадувати')),
                ('notify_time', models.TimeField(default='09:00', verbose_name='Час сповіщення')),
                ('repeat_days', models.IntegerField(default=1, verbose_name='Повторювати кожні N днів')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='bot.botuser', verbose_name='Користувач')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='clients.truck', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Налаштування нагадування',
                'verbose_name_plural': 'Налаштування нагадувань',
            },
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=50, verbose_name='Тип нагадування')),
                ('message_text', models.TextField(verbose_name='Текст повідомлення')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('delivery_error', models.TextField(blank=True, verbose_name='Помилка доставки')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('user_action', models.CharField(blank=True, max_length=50, verbose_name='Дія користувача')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Відправлено')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to='bot.botuser', verbose_name='Користувач')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Відправлене нагадування',
                'verbose_name_plural': 'Відправлені нагадування',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['telegram_id', 'role'], name='bot_botuser_telegra_4c3dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['phone_number'], name='bot_botuser_phone_n_e27629_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['-created_at', 'bot_user'], name='bot_message_created_9632f9_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['is_incoming', 'is_processed'], name='bot_message_is_inco_5d9d62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remindersettings',
            unique_together={('bot_user', 'truck', 'reminder_type')},
        ),
    ]
