# Generated by Django 5.2.6 on 2026-02-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('language_code', models.CharField(default='uk', max_length=10, verbose_name='Мова')),
                ('role', models.CharField(choices=[('guest', 'Гість'), ('owner', 'Власник'), ('admin', 'Адміністратор')], default='guest', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('assigned_trucks', models.ManyToManyField(blank=True, to='clients.truck', verbose_name='Закріплені авто')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Користувач бота',
                'verbose_name_plural': 'Користувачі бота',
            },
        ),
        migrations.CreateModel(
            name='BotMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('is_incoming', models.BooleanField(default=True, verbose_name='Вхідне?')),
                ('message_text', models.TextField(blank=True, verbose_name='Текст')),
                ('bot_response', models.TextField(blank=True, verbose_name='Відповідь бота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог повідомлення',
                'verbose_name_plural': 'Логи повідомлень',
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(default='maintenance', max_length=50, verbose_name='Тип нагадування')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Користувач')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Налаштування нагадування',
                'verbose_name_plural': 'Налаштування нагадувань',
                'unique_together': {('bot_user', 'truck', 'reminder_type')},
            },
        ),
    ]
