# Generated by Django 5.2.6 on 2025-11-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('clients', '0009_truck_clients_tru_license_1918f2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username Telegram')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Прізвище')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('owner', 'Власник'), ('driver', 'Водій'), ('guest', 'Гість')], default='guest', max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Сповіщення увімкнено')),
                ('notify_order_status', models.BooleanField(default=True, verbose_name='Сповіщення про статус замовлення')),
                ('notify_maintenance', models.BooleanField(default=True, verbose_name='Сповіщення про ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Остання активність')),
                ('allowed_trucks', models.ManyToManyField(blank=True, related_name='bot_users', to='clients.truck', verbose_name='Доступні вантажівки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Користувач бота',
                'verbose_name_plural': 'Користувачі бота',
                'ordering': ['-last_activity'],
            },
        ),
    ]
