# Generated by Django 5.2.6 on 2025-12-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageLog',
            new_name='BotMessageLog',
        ),
        migrations.RenameIndex(
            model_name='botmessagelog',
            new_name='bot_botmess_created_46e160_idx',
            old_name='bot_message_created_9632f9_idx',
        ),
        migrations.RenameIndex(
            model_name='botmessagelog',
            new_name='bot_botmess_is_inco_3a3a72_idx',
            old_name='bot_message_is_inco_5d9d62_idx',
        ),
    ]
