# Generated by Django 5.2.6 on 2026-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гість'), ('driver', 'Водій'), ('owner', 'Власник'), ('admin', 'Адміністратор')], default='guest', max_length=20, verbose_name='Роль'),
        ),
    ]
