# Generated by Django 5.2.6 on 2025-12-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botuser'),
        ('clients', '0009_truck_clients_tru_license_1918f2_idx_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_reminders_enabled', models.BooleanField(default=False, help_text='Глобальний перемикач для всієї системи нагадувань', verbose_name='Увімкнути нагадування про ТО')),
                ('reminder_days_before', models.PositiveIntegerField(default=7, help_text='Нагадування за X днів до планової дати', verbose_name='За скільки днів нагадувати (для дат)')),
                ('reminder_km_before', models.PositiveIntegerField(default=1000, help_text='Попередження за X км до планового ТО', verbose_name='За скільки км нагадувати')),
                ('reminder_time', models.TimeField(default='09:00', help_text='О котрій годині надсилати нагадування', verbose_name='Час відправки нагадувань')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Остання перевірка')),
            ],
            options={
                'verbose_name': 'Налаштування бота',
                'verbose_name_plural': 'Налаштування бота',
            },
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Користувач бота', 'verbose_name_plural': 'Користувачі бота'},
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='notify_maintenance',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='notify_order_status',
        ),
        migrations.AddField(
            model_name='botuser',
            name='enable_maintenance_reminders',
            field=models.BooleanField(default=True, help_text='Чи надсилати цьому користувачу нагадування про ТО', verbose_name='Увімкнути нагадування про ТО'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='reminder_telegram_enabled',
            field=models.BooleanField(default=True, help_text='Надсилати нагадування в Telegram', verbose_name='Telegram нагадування'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='allowed_trucks',
            field=models.ManyToManyField(blank=True, help_text='Для водіїв - до яких вантажівок має доступ', to='clients.truck', verbose_name='Доступні вантажівки'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Telegram chat_id користувача', null=True, unique=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Для власників - прив'язка до картки клієнта", null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone_number',
            field=models.CharField(blank=True, default=12345678, help_text='У форматі +380...', max_length=20, verbose_name='Номер телефону'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('owner', 'Власник'), ('driver', 'Водій'), ('guest', 'Гість')], default='guest', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, default='xxx', help_text='Telegram username (@username)', max_length=255, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('warning', 'Попередження (за 1000 км)'), ('urgent', 'Термінове (досягнуто інтервалу)')], max_length=20, verbose_name='Тип нагадування')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Відправлено')),
                ('delivery_status', models.CharField(choices=[('sent', 'Надіслано'), ('delivered', 'Доставлено'), ('failed', 'Помилка')], default='sent', max_length=20, verbose_name='Статус доставки')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Користувач')),
                ('service_reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.servicereminder', verbose_name='Нагадування про ТО')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Відправлене нагадування',
                'verbose_name_plural': 'Відправлені нагадування',
                'ordering': ['-sent_at'],
            },
        ),
    ]
