# Generated by Django 5.2.6 on 2026-01-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_messagelog_botmessagelog_and_more'),
        ('clients', '0014_client_deletion_reason_client_marked_for_deletion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotCommand',
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='bot_user',
        ),
        migrations.RemoveField(
            model_name='sentreminder',
            name='bot_user',
        ),
        migrations.RemoveField(
            model_name='sentreminder',
            name='truck',
        ),
        migrations.AlterModelOptions(
            name='botmessagelog',
            options={'verbose_name': 'Лог повідомлення', 'verbose_name_plural': 'Логи повідомлень'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Користувач бота', 'verbose_name_plural': 'Користувачі бота'},
        ),
        migrations.RemoveIndex(
            model_name='botmessagelog',
            name='bot_botmess_created_46e160_idx',
        ),
        migrations.RemoveIndex(
            model_name='botmessagelog',
            name='bot_botmess_is_inco_3a3a72_idx',
        ),
        migrations.RemoveIndex(
            model_name='botuser',
            name='bot_botuser_telegra_4c3dbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='botuser',
            name='bot_botuser_phone_n_e27629_idx',
        ),
        migrations.RemoveField(
            model_name='botmessagelog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='botmessagelog',
            name='handler_name',
        ),
        migrations.RemoveField(
            model_name='botmessagelog',
            name='message_data',
        ),
        migrations.RemoveField(
            model_name='botmessagelog',
            name='processing_time_ms',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='block_reason',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='total_messages',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='advance_days',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='advance_km',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='notify_time',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='repeat_days',
        ),
        migrations.AlterField(
            model_name='botmessagelog',
            name='bot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='botmessagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='botmessagelog',
            name='is_incoming',
            field=models.BooleanField(default=True, verbose_name='Вхідне?'),
        ),
        migrations.AlterField(
            model_name='botmessagelog',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botmessagelog',
            name='message_text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='botmessagelog',
            name='message_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='assigned_trucks',
            field=models.ManyToManyField(blank=True, to='clients.truck', verbose_name='Закріплені авто'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гість'), ('owner', 'Власник'), ('admin', 'Адміністратор')], default='guest', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='remindersettings',
            name='bot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='remindersettings',
            name='reminder_type',
            field=models.CharField(default='maintenance', max_length=50, verbose_name='Тип нагадування'),
        ),
        migrations.AlterField(
            model_name='remindersettings',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.truck', verbose_name='Вантажівка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConversationState',
        ),
        migrations.DeleteModel(
            name='SentReminder',
        ),
    ]
