# Generated by Django 5.2.6 on 2025-09-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я / Назва компанії")),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Прізвище (для фіз. осіб)')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Основний номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='IvecoBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва базової моделі')),
            ],
            options={
                'verbose_name': 'Базова модель Iveco',
                'verbose_name_plural': 'Базові моделі Iveco',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_model_name', models.CharField(help_text='Напр., 70C14 M.Y.2009', max_length=100, verbose_name='Точна назва моделі/модифікації')),
                ('full_vin', models.CharField(max_length=17, unique=True, verbose_name='Повний VIN-код')),
                ('last_seven_vin', models.CharField(blank=True, max_length=7, unique=True, verbose_name='Останні 7 знаків VIN')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Державний номер')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('current_mileage', models.PositiveIntegerField(default=0, verbose_name='Поточний пробіг (км)')),
                ('transmission_type', models.CharField(choices=[('manual', 'Механічна'), ('automatic', 'Автоматична'), ('robot', 'Робот')], max_length=10, verbose_name='Тип КПП')),
                ('emission_standard', models.CharField(choices=[('unknown', 'Не вказано'), ('euro3', 'Євро-3'), ('euro4', 'Євро-4'), ('euro5', 'Євро-5'), ('euro6', 'Євро-6')], default='unknown', max_length=10, verbose_name='Стандарт викидів')),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.ivecobasemodel', verbose_name='Базова модель (родина)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Вантажівка',
                'verbose_name_plural': 'Вантажівки',
            },
        ),
    ]
