# Generated by Django 5.2.6 on 2026-02-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IvecoBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Базова модель')),
            ],
            options={
                'verbose_name': 'Базова модель Iveco',
                'verbose_name_plural': 'Базові моделі Iveco',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Основний номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID чату Telegram')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Адміністратор бота')),
                ('marked_for_deletion', models.BooleanField(default=False, verbose_name='Позначено на видалення')),
                ('marked_for_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата позначення')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Причина видалення')),
                ('marked_for_deletion_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_model_name', models.CharField(max_length=100, verbose_name='Конкретна модель (напр. 35C15)')),
                ('full_vin', models.CharField(max_length=17, unique=True, verbose_name='Повний VIN')),
                ('last_seven_vin', models.CharField(db_index=True, editable=False, max_length=7, unique=True, verbose_name='Останні 7 символів VIN')),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='Номерний знак')),
                ('euro_standard', models.CharField(blank=True, choices=[('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], max_length=10, null=True, verbose_name='Євростандарт викидів')),
                ('marked_for_deletion', models.BooleanField(default=False, verbose_name='Позначено на видалення')),
                ('marked_for_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата позначення')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Причина видалення')),
                ('base_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.ivecobasemodel', verbose_name='Базова модель')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Власник')),
                ('marked_for_deletion_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення')),
            ],
            options={
                'verbose_name': 'Вантажівка',
                'verbose_name_plural': 'Вантажівки',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Попередній номерний знак')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Попередній власник')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Запис історії',
                'verbose_name_plural': 'Історія володіння',
                'ordering': ['-change_date'],
            },
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['license_plate'], name='clients_tru_license_1918f2_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['last_seven_vin'], name='clients_tru_last_se_12d495_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['client', 'license_plate'], name='clients_tru_client__60da9f_idx'),
        ),
    ]
