# Generated by Django 5.2.6 on 2026-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Номерний знак'),
        ),
    ]
