# Generated by Django 5.2.6 on 2025-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID чату Telegram'),
        ),
    ]
