# Generated by Django 5.2.6 on 2025-11-12 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='emission_standard',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='transmission_type',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='year_of_manufacture',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='ivecobasemodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Базова модель'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='base_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.ivecobasemodel', verbose_name='Базова модель'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='full_vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='Повний VIN'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='last_seven_vin',
            field=models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Останні 7 символів VIN'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номерний знак'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='specific_model_name',
            field=models.CharField(max_length=100, verbose_name='Конкретна модель (напр. 35C15)'),
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Попередній номерний знак')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Попередній власник')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Запис історії',
                'verbose_name_plural': 'Історія володіння',
                'ordering': ['-change_date'],
            },
        ),
    ]
