# Generated by Django 5.2.6 on 2025-11-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_created_at_remove_client_surname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['license_plate'], 'verbose_name': 'Вантажівка', 'verbose_name_plural': 'Вантажівки'},
        ),
    ]
