# Generated by Django 5.2.6 on 2026-03-24 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientfeature_restrict_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='marked_for_deletion_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='full_vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)], verbose_name='Повний VIN'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='marked_for_deletion_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення'),
        ),
    ]
