# Generated by Django 5.2.6 on 2025-11-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_options_alter_truck_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ivecobasemodel',
            options={'ordering': ['name'], 'verbose_name': 'Базова модель Iveco', 'verbose_name_plural': 'Базові моделі Iveco'},
        ),
    ]
