# Generated by Django 5.2.6 on 2025-11-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_ivecobasemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('EURO3', 'Євро-3'), ('EURO4', 'Євро-4'), ('EURO5', 'Євро-5'), ('EURO6', 'Євро-6')], max_length=10, null=True, verbose_name='Євростандарт викидів'),
        ),
    ]
