# Generated by Django 5.2.6 on 2025-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_truck_euro_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='last_seven_vin',
            field=models.CharField(db_index=True, editable=False, max_length=7, unique=True, verbose_name='Останні 7 символів VIN'),
        ),
    ]
