# Generated by Django 5.2.6 on 2025-11-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_truck_last_seven_vin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['license_plate'], name='clients_tru_license_1918f2_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['last_seven_vin'], name='clients_tru_last_se_12d495_idx'),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['client', 'license_plate'], name='clients_tru_client__60da9f_idx'),
        ),
    ]
