# Generated by Django 5.2.6 on 2025-12-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_truck_clients_tru_license_1918f2_idx_and_more'),
        ('clients', '0010_client_is_bot_admin'),
    ]

    operations = [
    ]
