# Generated by Django 5.2.6 on 2025-12-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_merge_20251215_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_bot_admin',
        ),
        migrations.AddField(
            model_name='client',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Адміністратор бота'),
        ),
    ]
