# Generated by Django 5.2.6 on 2025-12-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_merge_20251214_1659'),
        ('clients', '0011_merge_20251215_1551'),
    ]

    operations = [
    ]
