# Generated by Django 5.2.6 on 2025-12-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_merge_20251215_1509'),
        ('clients', '0012_remove_client_is_bot_admin_client_is_admin'),
    ]

    operations = [
    ]
