[pytest]
DJANGO_SETTINGS_MODULE = my_iveco_crm.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short
testpaths = clients orders inventory
pythonpath = . ..

[coverage:run]
source = clients,orders,inventory
omit = */migrations/*,*/tests/*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
