# Generated by Django 5.2.6 on 2025-09-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва запчастини')),
                ('sku_code', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
            ],
            options={
                'verbose_name': 'Запчастина',
                'verbose_name_plural': 'Запчастини',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part', verbose_name='Запчастина')),
                ('service_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='orders.servicework', verbose_name='Робота')),
            ],
            options={
                'verbose_name': 'Використана запчастина',
                'verbose_name_plural': 'Використані запчастини',
                'unique_together': {('service_work', 'part')},
            },
        ),
    ]
