# Generated by Django 5.2.6 on 2026-02-22 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category_type', models.CharField(default='other', max_length=50, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('default_change_interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни (км)')),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за одиницю')),
            ],
            options={
                'verbose_name': 'Використана запчастина',
                'verbose_name_plural': 'Використані запчастини',
                'ordering': ['part__name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Собівартість')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна продажу')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залишок')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мін. залишок')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('l', 'л'), ('kg', 'кг'), ('pack', 'уп'), ('m', 'м')], default='pcs', max_length=10, verbose_name='Одиниця виміру')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('viscosity', models.CharField(blank=True, max_length=20, verbose_name="В'язкість")),
                ('volume_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Об'єм в упаковці")),
                ('specifications', models.TextField(blank=True, verbose_name='Специфікації')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('address_in_stock', models.CharField(blank=True, max_length=100, verbose_name='Адреса на складі')),
                ('marked_for_deletion', models.BooleanField(default=False, verbose_name='Позначено на видалення')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Причина видалення')),
                ('marked_for_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата позначення')),
                ('marked_for_deletion_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Кількість')),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Зарезервовано')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Місце зберігання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Залишок на складі',
                'verbose_name_plural': 'Залишки на складі',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Надходження'), ('out', 'Витрата'), ('transfer', 'Переміщення'), ('adjustment', 'Інвентаризація'), ('return', 'Повернення'), ('write_off', 'Списання')], max_length=20, verbose_name='Тип руху')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Постачальник')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер накладної')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупівельна ціна')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рух товару',
                'verbose_name_plural': 'Рух товарів',
                'ordering': ['-created_at'],
            },
        ),
    ]
