# Generated by Django 5.2.6 on 2026-02-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.serviceorder', verbose_name='Наряд-замовлення'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.subcategory', verbose_name='Підкатегорія'),
        ),
        migrations.AddField(
            model_name='usedpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Запчастина'),
        ),
        migrations.AddField(
            model_name='usedpart',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_parts', to='orders.serviceorder', verbose_name='Наряд-замовлення'),
        ),
        migrations.AddField(
            model_name='usedpart',
            name='service_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='orders.servicework', verbose_name='Робота'),
        ),
        migrations.AddField(
            model_name='usedpart',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_movements', to='inventory.warehouse', verbose_name='Зі складу'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_movements', to='inventory.warehouse', verbose_name='На склад'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('warehouse', 'product')},
        ),
    ]
