# Generated by Django 5.2.6 on 2025-11-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія запчастин',
                'verbose_name_plural': 'Категорії запчастин',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='part',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Собівартість'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='part',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Залишок на складі'),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код/Артикул'),
        ),
        migrations.AlterField(
            model_name='usedpart',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кількість'),
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partcategory', verbose_name='Категорія'),
        ),
    ]
