# Generated by Django 5.2.6 on 2025-11-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_partcategory_rename_price_part_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partcategory',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Категорія запчастин', 'verbose_name_plural': 'Категорії запчастин'},
        ),
        migrations.AddField(
            model_name='partcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.partcategory', verbose_name='Батьківська категорія'),
        ),
        migrations.AlterField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Собівартість'),
        ),
    ]
