# Generated by Django 5.2.6 on 2026-04-02 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_marked_for_deletion_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_folders', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Папка замовлення',
                'verbose_name_plural': 'Папки замовлень',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Назва')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кількість')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Одиниця')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Замовлено')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='Замовлено о')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.orderfolder', verbose_name='Папка')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to=settings.AUTH_USER_MODEL, verbose_name='Замовив')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлень',
                'ordering': ['created_at'],
            },
        ),
    ]
