# Generated by Django 5.2.6 on 2025-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_partcategory_options_partcategory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='substitutes',
            field=models.ManyToManyField(blank=True, to='inventory.part', verbose_name='Замінники (аналоги)'),
        ),
    ]
