# Generated by Django 5.2.6 on 2026-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_order_folder_and_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('retail', 'Роздрібний'), ('wholesale', 'Оптовий'), ('other', 'Інший')], default='retail', max_length=20, verbose_name='Тип складу'),
        ),
    ]
