# Generated by Django 5.2.6 on 2025-11-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_part_substitutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='address_in_stock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса на складі (Полиця, Секція)'),
        ),
        migrations.AddField(
            model_name='part',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки'),
        ),
    ]
