# Generated by Django 5.2.6 on 2026-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfolder',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Архівовано'),
        ),
        migrations.AddField(
            model_name='orderfolder',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архіві'),
        ),
    ]
