# Generated by Django 5.2.6 on 2025-11-26 21:03

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_part_address_in_stock_part_notes'),
        ('orders', '0021_alter_filtertype_replacement_interval_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category_type', models.CharField(choices=[('oil', 'Оливи'), ('filter', 'Фільтри'), ('fluid', 'Технічні рідини'), ('washer', 'Омивачі'), ('part', 'Запчастини'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип категорії')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Іконка')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія товарів',
                'verbose_name_plural': 'Категорії товарів',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': 'Товар/Запчастина', 'verbose_name_plural': 'Товари/Запчастини'},
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 26, 21, 3, 26, 987474, tzinfo=datetime.timezone.utc), verbose_name='Створено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='part',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сповіщення коли залишок нижче цього значення', max_digits=10, verbose_name='Мінімальний залишок'),
        ),
        migrations.AddField(
            model_name='part',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за літр'),
        ),
        migrations.AddField(
            model_name='part',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Специфікації'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт'), ('l', 'л'), ('kg', 'кг'), ('pack', 'уп'), ('m', 'м')], default='pcs', max_length=10, verbose_name='Одиниця виміру'),
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AddField(
            model_name='part',
            name='viscosity',
            field=models.CharField(blank=True, max_length=20, verbose_name="В'язкість"),
        ),
        migrations.AddField(
            model_name='part',
            name='volume_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Наприклад: 20 літрів в каністрі', max_digits=10, null=True, verbose_name="Об'єм в упаковці"),
        ),
        migrations.AlterField(
            model_name='part',
            name='address_in_stock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса на складі'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Застаріле поле, використовуйте subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partcategory', verbose_name='Категорія (стара)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Залишок (заг.)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='part',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна продажу'),
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('default_change_interval_km', models.PositiveIntegerField(blank=True, help_text='Стандартний інтервал заміни для цього типу', null=True, verbose_name='Інтервал заміни (км)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.productcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорія товарів',
                'verbose_name_plural': 'Підкатегорії товарів',
                'ordering': ['category', 'sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productsubcategory', verbose_name='Підкатегорія (нова)'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Надходження'), ('out', 'Витрата'), ('transfer', 'Переміщення'), ('adjustment', 'Інвентаризація'), ('return', 'Повернення'), ('write_off', 'Списання')], max_length=20, verbose_name='Тип руху')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Кількість')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Постачальник')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер накладної')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Закупівельна ціна')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.part', verbose_name='Товар')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.serviceorder', verbose_name='Наряд-замовлення')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='inventory.warehouse', verbose_name='Зі складу')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='inventory.warehouse', verbose_name='На склад')),
            ],
            options={
                'verbose_name': 'Рух товару',
                'verbose_name_plural': 'Рух товарів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usedpart',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Кількість')),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Зарезервовано')),
                ('location', models.CharField(blank=True, help_text='Полиця, секція, тощо', max_length=100, verbose_name='Місце зберігання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.part', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Залишок на складі',
                'verbose_name_plural': 'Залишки на складі',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
