# Generated by Django 5.2.6 on 2025-12-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productcategory_warehouse_alter_part_options_and_more'),
        ('orders', '0021_alter_filtertype_replacement_interval_km'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedpart',
            options={'ordering': ['part__name'], 'verbose_name': 'Використана запчастина', 'verbose_name_plural': 'Використані запчастини'},
        ),
        migrations.AlterUniqueTogether(
            name='usedpart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usedpart',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_parts', to='orders.serviceorder', verbose_name='Наряд-замовлення'),
        ),
        migrations.AddField(
            model_name='usedpart',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заповнюється автоматично з selling_price товару', max_digits=10, null=True, verbose_name='Ціна за одиницю'),
        ),
        migrations.AlterField(
            model_name='usedpart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='usedpart',
            name='service_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='orders.servicework', verbose_name='Робота'),
        ),
    ]
