# Generated by Django 5.2.6 on 2026-01-07 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_usedpart_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='deletion_reason',
            field=models.TextField(blank=True, verbose_name='Причина видалення'),
        ),
        migrations.AddField(
            model_name='part',
            name='marked_for_deletion',
            field=models.BooleanField(default=False, verbose_name='Позначено на видалення'),
        ),
        migrations.AddField(
            model_name='part',
            name='marked_for_deletion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата позначення'),
        ),
        migrations.AddField(
            model_name='part',
            name='marked_for_deletion_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_marked_for_deletion', to=settings.AUTH_USER_MODEL, verbose_name='Позначив на видалення'),
        ),
    ]
