# Generated by Django 5.2.6 on 2026-02-15 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Кількість (л/шт)')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробіг при заміні (км)')),
                ('next_change_mileage', models.PositiveIntegerField(blank=True, help_text='Розраховується автоматично на основі інтервалу підкатегорії', null=True, verbose_name='Наступна заміна (км)')),
                ('next_change_date', models.DateField(blank=True, help_text='Розраховується автоматично: +1 рік від дати виконання', null=True, verbose_name='Наступна заміна (дата)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Загальна вартість')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Виконав')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Використаний товар')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluid_changes', to='orders.serviceorder', verbose_name='Наряд-замовлення')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.subcategory', verbose_name='Тип рідини/оливи')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_changes', to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Запис про заміну рідини',
                'verbose_name_plural': 'Історія замін рідин',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('default_interval_km', models.PositiveIntegerField(blank=True, help_text='Наприклад: 20000 км для моторної оливи', null=True, verbose_name='Інтервал за пробігом (км)')),
                ('default_interval_months', models.PositiveIntegerField(blank=True, help_text='Наприклад: 12 місяців для моторної оливи', null=True, verbose_name='Інтервал за часом (місяців)')),
                ('default_priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('critical', 'Критичний')], default='medium', max_length=20, verbose_name='Пріоритет за замовчуванням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('related_subcategories', models.ManyToManyField(blank=True, help_text='Коли змінюється товар з цієї підкатегорії - створюється нагадування цього типу', to='inventory.subcategory', verbose_name="Пов'язані підкатегорії товарів")),
            ],
            options={
                'verbose_name': 'Тип технічного обслуговування',
                'verbose_name_plural': 'Типи технічного обслуговування',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('reminder_type', models.CharField(choices=[('mileage', 'За пробігом'), ('date', 'За датою'), ('both', 'За пробігом або датою')], default='both', max_length=20, verbose_name='Тип нагадування')),
                ('target_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цільовий пробіг (км)')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Цільова дата')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('notified', 'Сповіщено'), ('completed', 'Виконано'), ('overdue', 'Прострочено'), ('dismissed', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('critical', 'Критичний')], default='medium', max_length=20, verbose_name='Пріоритет')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('completed_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.serviceorder', verbose_name='Виконане замовлення')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.truck', verbose_name='Вантажівка')),
                ('service_type', models.ForeignKey(blank=True, help_text='Конкретний тип ТО (заміна оливи, колодок і т.д.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.servicetype', verbose_name='Тип обслуговування')),
            ],
            options={
                'verbose_name': 'Нагадування про ТО',
                'verbose_name_plural': 'Нагадування про ТО',
                'ordering': ['status', 'target_date', 'target_mileage'],
            },
        ),
        migrations.CreateModel(
            name='TruckFluidSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Об'єм заправки (л)")),
                ('change_interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни (км)')),
                ('change_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Інтервал заміни (місяців)')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('alternative_products', models.ManyToManyField(blank=True, related_name='alternative_for_trucks', to='inventory.product', verbose_name='Альтернативні товари')),
                ('recommended_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_trucks', to='inventory.product', verbose_name='Рекомендований товар')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory', verbose_name='Тип рідини')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_specs', to='clients.truck', verbose_name='Вантажівка')),
            ],
            options={
                'verbose_name': 'Специфікація рідин',
                'verbose_name_plural': 'Специфікації рідин',
                'unique_together': {('truck', 'subcategory')},
            },
        ),
    ]
