# Generated by Django 5.2.6 on 2025-12-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_usedpart_options_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereminder',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='fluidchangerecord',
            name='next_change_date',
            field=models.DateField(blank=True, help_text='Розраховується автоматично: +1 рік від дати виконання', null=True, verbose_name='Наступна заміна (дата)'),
        ),
        migrations.AlterField(
            model_name='fluidchangerecord',
            name='next_change_mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Розраховується автоматично на основі інтервалу підкатегорії', null=True, verbose_name='Наступна заміна (км)'),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('default_interval_km', models.PositiveIntegerField(blank=True, help_text='Наприклад: 20000 км для моторної оливи', null=True, verbose_name='Інтервал за пробігом (км)')),
                ('default_interval_months', models.PositiveIntegerField(blank=True, help_text='Наприклад: 12 місяців для моторної оливи', null=True, verbose_name='Інтервал за часом (місяців)')),
                ('default_priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('critical', 'Критичний')], default='medium', max_length=20, verbose_name='Пріоритет за замовчуванням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('related_subcategories', models.ManyToManyField(blank=True, help_text='Коли змінюється товар з цієї підкатегорії - створюється нагадування цього типу', to='inventory.productsubcategory', verbose_name="Пов'язані підкатегорії товарів")),
            ],
            options={
                'verbose_name': 'Тип технічного обслуговування',
                'verbose_name_plural': 'Типи технічного обслуговування',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicereminder',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Конкретний тип ТО (заміна оливи, колодок і т.д.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.servicetype', verbose_name='Тип обслуговування'),
        ),
    ]
