# Generated by Django 5.2.6 on 2026-01-31 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_category_remove_part_category_and_more'),
        ('maintenance', '0002_remove_servicereminder_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluidchangerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Використаний товар'),
        ),
        migrations.AlterField(
            model_name='fluidchangerecord',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.subcategory', verbose_name='Тип рідини/оливи'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='related_subcategories',
            field=models.ManyToManyField(blank=True, help_text='Коли змінюється товар з цієї підкатегорії - створюється нагадування цього типу', to='inventory.subcategory', verbose_name="Пов'язані підкатегорії товарів"),
        ),
        migrations.AlterField(
            model_name='truckfluidspec',
            name='alternative_products',
            field=models.ManyToManyField(blank=True, related_name='alternative_for_trucks', to='inventory.product', verbose_name='Альтернативні товари'),
        ),
        migrations.AlterField(
            model_name='truckfluidspec',
            name='recommended_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_trucks', to='inventory.product', verbose_name='Рекомендований товар'),
        ),
        migrations.AlterField(
            model_name='truckfluidspec',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory', verbose_name='Тип рідини'),
        ),
    ]
