# Generated by Django 5.2.6 on 2026-02-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вхід в систему'), ('logout', 'Вихід з системи'), ('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('view', 'Перегляд'), ('export', 'Експорт')], max_length=20, verbose_name='Тип дії')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name="ID об'єкта")),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Представлення')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Зміни')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/час')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Журнал дій',
                'verbose_name_plural': 'Журнал дій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('manager', 'Менеджер'), ('mechanic', 'Механік'), ('storekeeper', 'Комірник'), ('accountant', 'Бухгалтер')], default='mechanic', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Посада')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('warehouses', models.ManyToManyField(blank=True, related_name='staff', to='inventory.warehouse', verbose_name='Доступні склади')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
