# Generated by Django 5.2.6 on 2026-03-12 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_user_account'),
        ('orders', '0007_alter_repairphoto_image_alter_serviceorder_car_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name="Ім'я клієнта")),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клієнта')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Держномер авто')),
                ('scheduled_dt', models.DateTimeField(verbose_name='Дата та час запису')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Тривалість (хв)')),
                ('service_type', models.CharField(choices=[('diagnosis', 'Діагностика'), ('maintenance', 'Технічне обслуговування'), ('repair', 'Ремонт'), ('other', 'Інше')], default='repair', max_length=20, verbose_name='Тип послуги')),
                ('description', models.TextField(blank=True, verbose_name='Опис/коментар')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено'), ('no_show', "Не з'явився")], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Підтвердження надіслано')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Нагадування надіслано')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client', verbose_name='Клієнт (з бази)')),
                ('converted_to_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_appointment', to='orders.serviceorder', verbose_name='Наряд-замовлення')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Запис на СТО',
                'verbose_name_plural': 'Записи на СТО',
                'ordering': ['scheduled_dt'],
            },
        ),
    ]
