name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SSHPASS: ${{ secrets.DO_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }} << 'EOF'

          cd /home/ubuntu/truckmaster/my_iveco_crm

          # 1. Примусово оновлюємо код
          git fetch origin
          git reset --hard origin/main

          # 2. Активуємо venv
          source /home/ubuntu/truckmaster/my_iveco_crm/venv/bin/activate

          # 3. ВИПРАВЛЕННЯ ДЛЯ UBUNTU (PEP 668)
          # Встановлюємо pip install, ігноруючи системні помилки
          pip install -r requirements.txt --break-system-packages

          # 4. Запускаємо міграції
          python manage.py migrate

          # 5. Збираємо статику
          python manage.py collectstatic --noinput

          # 6. Перезапускаємо сервіси
          sudo systemctl restart gunicorn
          sudo systemctl restart telegram_bot
        EOF