name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SSHPASS: ${{ secrets.DO_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }} << 'EOF'
          
          # 1. Переходимо в правильну папку проєкту
          cd /home/ubuntu/truckmaster/my_iveco_crm
          
          # 2. Примусово скидаємо локальні зміни і оновлюємось
          git fetch origin
          git reset --hard origin/main
          
          # 3. Активуємо віртуальне середовище (ПРАВИЛЬНИЙ ШЛЯХ)
          source /home/ubuntu/truckmaster/my_iveco_crm/venv/bin/activate
          
          # 4. Встановлюємо/оновлюємо бібліотеки
          # Використовуємо --break-system-packages, щоб обійти помилку Ubuntu
          pip install -r requirements.txt --break-system-packages
          
          # 5. Застосовуємо міграції бази даних
          python manage.py migrate
          
          # 6. Збираємо статичні файли (для адмінки)
          python manage.py collectstatic --noinput
          
          # 7. Перезапускаємо Gunicorn (тепер без пароля)
          sudo systemctl restart gunicorn
          
          # 8. Перезапускаємо Telegram-бота (тепер без пароля)
          sudo systemctl restart telegram_bot
        EOF